FROM node:16-alpine

USER root

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

COPY .env \
  package.json \
  tsconfig.json ./

RUN npm install

RUN echo "--> permissions" && \
  echo "--> Fixing permissions" && \
  echo "node  ALL = ( ALL ) NOPASSWD: ALL" >> /etc/sudoers && \
  chown -R node:node /home/node

COPY ./src ./src

ENV PORT=4000

USER node

EXPOSE 4000

CMD ["npm", "run", "start-dev"]